### PR TITLE
HLM-5361, HLM-5362 : updated common models with EgovModel and EgovOfflineModel

### PR DESCRIPTION
**Pull request by kanishq-egov**

### CODE REVIEW

**Comment by kanishq-egov** [comment]
@coderabbitai review

**Comment by kavi-egov** [comment]
@coderabbitai review

**Comment by kanishq-egov** [comment]
@coderabbitai review

**Comment by kanishq-egov** [comment]
@coderabbitai summary

**Comment by kanishq-egov** [comment]
@coderabbitai review

**Comment by kanishq-egov** [comment]
@coderabbitai Please re-review this PR.

**Review by kavi-egov — APPROVED** [review]

**Pull request merged**
